#if PLAYMAKER
using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;
using HutongGames.PlayMaker.Actions;
using HutongGames.PlayMaker;
using UnityEngine;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Fetch row data for AllFields meta from GameRepo database by row's id")]
		public partial class AllFieldsGetById : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityAudioClip _ufle12jhs77_unityAudioClipField;
			public static BansheeGz.BGDatabase.BGFieldUnityAudioClip _unityAudioClipField
			{
				get
				{
					if(_ufle12jhs77_unityAudioClipField==null || _ufle12jhs77_unityAudioClipField.IsDeleted) _ufle12jhs77_unityAudioClipField=(BansheeGz.BGDatabase.BGFieldUnityAudioClip) MetaDefault.GetField(new BGId(4825868847504134564,2434145578512012470));
					return _ufle12jhs77_unityAudioClipField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityFont _ufle12jhs77_unityFontField;
			public static BansheeGz.BGDatabase.BGFieldUnityFont _unityFontField
			{
				get
				{
					if(_ufle12jhs77_unityFontField==null || _ufle12jhs77_unityFontField.IsDeleted) _ufle12jhs77_unityFontField=(BansheeGz.BGDatabase.BGFieldUnityFont) MetaDefault.GetField(new BGId(5599513016958909782,3230565417687017906));
					return _ufle12jhs77_unityFontField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityMaterial _ufle12jhs77_unityMaterialField;
			public static BansheeGz.BGDatabase.BGFieldUnityMaterial _unityMaterialField
			{
				get
				{
					if(_ufle12jhs77_unityMaterialField==null || _ufle12jhs77_unityMaterialField.IsDeleted) _ufle12jhs77_unityMaterialField=(BansheeGz.BGDatabase.BGFieldUnityMaterial) MetaDefault.GetField(new BGId(4908436488796322532,14604855426035245470));
					return _ufle12jhs77_unityMaterialField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityObject _ufle12jhs77_unityObjectField;
			public static BansheeGz.BGDatabase.BGFieldUnityObject _unityObjectField
			{
				get
				{
					if(_ufle12jhs77_unityObjectField==null || _ufle12jhs77_unityObjectField.IsDeleted) _ufle12jhs77_unityObjectField=(BansheeGz.BGDatabase.BGFieldUnityObject) MetaDefault.GetField(new BGId(4839494584961834536,2008211144111203502));
					return _ufle12jhs77_unityObjectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_unityPrefabField;
			public static BansheeGz.BGDatabase.BGFieldUnityPrefab _unityPrefabField
			{
				get
				{
					if(_ufle12jhs77_unityPrefabField==null || _ufle12jhs77_unityPrefabField.IsDeleted) _ufle12jhs77_unityPrefabField=(BansheeGz.BGDatabase.BGFieldUnityPrefab) MetaDefault.GetField(new BGId(5194638669282079054,358716183513871039));
					return _ufle12jhs77_unityPrefabField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_unitySpriteField;
			public static BansheeGz.BGDatabase.BGFieldUnitySprite _unitySpriteField
			{
				get
				{
					if(_ufle12jhs77_unitySpriteField==null || _ufle12jhs77_unitySpriteField.IsDeleted) _ufle12jhs77_unitySpriteField=(BansheeGz.BGDatabase.BGFieldUnitySprite) MetaDefault.GetField(new BGId(4669431258759682220,7562358095153627323));
					return _ufle12jhs77_unitySpriteField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture _ufle12jhs77_unityTextureField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture _unityTextureField
			{
				get
				{
					if(_ufle12jhs77_unityTextureField==null || _ufle12jhs77_unityTextureField.IsDeleted) _ufle12jhs77_unityTextureField=(BansheeGz.BGDatabase.BGFieldUnityTexture) MetaDefault.GetField(new BGId(5370240882512399954,13796868656774551469));
					return _ufle12jhs77_unityTextureField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture2d _ufle12jhs77_unityTexture2dField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture2d _unityTexture2dField
			{
				get
				{
					if(_ufle12jhs77_unityTexture2dField==null || _ufle12jhs77_unityTexture2dField.IsDeleted) _ufle12jhs77_unityTexture2dField=(BansheeGz.BGDatabase.BGFieldUnityTexture2d) MetaDefault.GetField(new BGId(4667378435442547491,6566432755137170102));
					return _ufle12jhs77_unityTexture2dField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _ufle12jhs77_spriteMultiple;
			public static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _spriteMultiple
			{
				get
				{
					if(_ufle12jhs77_spriteMultiple==null || _ufle12jhs77_spriteMultiple.IsDeleted) _ufle12jhs77_spriteMultiple=(BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple) MetaDefault.GetField(new BGId(5428695482298794185,14203080233642320273));
					return _ufle12jhs77_spriteMultiple;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity id")]
			public FsmString _Id;
			[UIHint(UIHint.Variable)]
			public FsmString name;
			[UIHint(UIHint.Variable)]
			public FsmBool boolField;
			[UIHint(UIHint.Variable)]
			public FsmFloat floatField;
			[UIHint(UIHint.Variable)]
			public FsmInt intField;
			[UIHint(UIHint.Variable)]
			public FsmString stringField;
			[UIHint(UIHint.Variable)]
			public FsmString textField;
			[UIHint(UIHint.Variable)]
			public FsmColor colorField;
			[UIHint(UIHint.Variable)]
			public FsmQuaternion quaternionField;
			[UIHint(UIHint.Variable)]
			public FsmRect rectField;
			[UIHint(UIHint.Variable)]
			public FsmVector2 vector2Field;
			[UIHint(UIHint.Variable)]
			public FsmVector3 vector3Field;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.AudioClip))]
			public FsmObject unityAudioClipField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Font))]
			public FsmObject unityFontField;
			[UIHint(UIHint.Variable)]
			public FsmMaterial unityMaterialField;
			[UIHint(UIHint.Variable)]
			public FsmObject unityObjectField;
			[UIHint(UIHint.Variable)]
			public FsmGameObject unityPrefabField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Sprite))]
			public FsmObject unitySpriteField;
			[UIHint(UIHint.Variable)]
			public FsmTexture unityTextureField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Texture2D))]
			public FsmObject unityTexture2dField;
			[UIHint(UIHint.Variable)]
			[ArrayEditor(VariableType.Object)]
			public FsmArray spriteMultiple;
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			public override void Reset()
			{
				_Id = null;
				_Index = null;
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
				unityAudioClipField = null;
				unityFontField = null;
				unityMaterialField = null;
				unityObjectField = null;
				unityPrefabField = null;
				unitySpriteField = null;
				unityTextureField = null;
				unityTexture2dField = null;
				spriteMultiple = null;
			}
			public override void OnEnter()
			{
				if (_Id.IsNone || _Id.Value==null)
				{
					Debug.LogWarning("Required field _Id is not set");
					return;
				}
				var id = BGId.Empty;
				try
				{
					id = new BGId(_Id.Value);
				}
				catch
				{
					Debug.LogWarning("Unable to parse id " + _Id.Value);
					return;
				}
				var entity = MetaDefault[id];
				if (entity == null)
				{
					Debug.LogWarning("No entity found, id=" + id);
					return;
				}
				var index = entity.Index;
				if(!_Index.IsNone)
				{
					_Index.Value = index;
				}
				if(!name.IsNone)
				{
					name.Value = _name[index];
				}
				if(!boolField.IsNone)
				{
					boolField.Value = _boolField[index];
				}
				if(!floatField.IsNone)
				{
					floatField.Value = _floatField[index];
				}
				if(!intField.IsNone)
				{
					intField.Value = _intField[index];
				}
				if(!stringField.IsNone)
				{
					stringField.Value = _stringField[index];
				}
				if(!textField.IsNone)
				{
					textField.Value = _textField[index];
				}
				if(!colorField.IsNone)
				{
					colorField.Value = _colorField[index];
				}
				if(!quaternionField.IsNone)
				{
					quaternionField.Value = _quaternionField[index];
				}
				if(!rectField.IsNone)
				{
					rectField.Value = _rectField[index];
				}
				if(!vector2Field.IsNone)
				{
					vector2Field.Value = _vector2Field[index];
				}
				if(!vector3Field.IsNone)
				{
					vector3Field.Value = _vector3Field[index];
				}
				if(!unityAudioClipField.IsNone)
				{
					unityAudioClipField.Value = _unityAudioClipField[index];
				}
				if(!unityFontField.IsNone)
				{
					unityFontField.Value = _unityFontField[index];
				}
				if(!unityMaterialField.IsNone)
				{
					unityMaterialField.Value = _unityMaterialField[index];
				}
				if(!unityObjectField.IsNone)
				{
					unityObjectField.Value = _unityObjectField[index];
				}
				if(!unityPrefabField.IsNone)
				{
					unityPrefabField.Value = _unityPrefabField[index];
				}
				if(!unitySpriteField.IsNone)
				{
					unitySpriteField.Value = _unitySpriteField[index];
				}
				if(!unityTextureField.IsNone)
				{
					unityTextureField.Value = _unityTextureField[index];
				}
				if(!unityTexture2dField.IsNone)
				{
					unityTexture2dField.Value = _unityTexture2dField[index];
				}
				if(!spriteMultiple.IsNone)
				{
					var list = _spriteMultiple[index];
					if (list != null && list.Length > 0) spriteMultiple.Values = list;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Set row data for AllFields meta from GameRepo database by row's id")]
		public partial class AllFieldsSetById : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity id")]
			public FsmString _Id;
			public FsmString name;
			public FsmBool boolField;
			public FsmFloat floatField;
			public FsmInt intField;
			public FsmString stringField;
			public FsmString textField;
			public FsmColor colorField;
			public FsmQuaternion quaternionField;
			public FsmRect rectField;
			public FsmVector2 vector2Field;
			public FsmVector3 vector3Field;
			public override void Reset()
			{
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
			}
			public override void OnEnter()
			{
				if (_Id.IsNone || _Id.Value==null)
				{
					Debug.LogWarning("Required field _Id is not set");
					return;
				}
				var id = BGId.Empty;
				try
				{
					id = new BGId(_Id.Value);
				}
				catch
				{
					Debug.LogWarning("Unable to parse id " + _Id.Value);
					return;
				}
				var entity = MetaDefault[id];
				if (entity == null)
				{
					Debug.LogWarning("No entity found, id=" + id);
					return;
				}
				var index = entity.Index;
				if(!name.IsNone)
				{
					_name[index] = name.Value;
				}
				if(!boolField.IsNone)
				{
					_boolField[index] = boolField.Value;
				}
				if(!floatField.IsNone)
				{
					_floatField[index] = floatField.Value;
				}
				if(!intField.IsNone)
				{
					_intField[index] = intField.Value;
				}
				if(!stringField.IsNone)
				{
					_stringField[index] = stringField.Value;
				}
				if(!textField.IsNone)
				{
					_textField[index] = textField.Value;
				}
				if(!colorField.IsNone)
				{
					_colorField[index] = colorField.Value;
				}
				if(!quaternionField.IsNone)
				{
					_quaternionField[index] = quaternionField.Value;
				}
				if(!rectField.IsNone)
				{
					_rectField[index] = rectField.Value;
				}
				if(!vector2Field.IsNone)
				{
					_vector2Field[index] = vector2Field.Value;
				}
				if(!vector3Field.IsNone)
				{
					_vector3Field[index] = vector3Field.Value;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Fetch row data for AllFields meta from GameRepo database by row's index")]
		public partial class AllFieldsGetByIndex : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityAudioClip _ufle12jhs77_unityAudioClipField;
			public static BansheeGz.BGDatabase.BGFieldUnityAudioClip _unityAudioClipField
			{
				get
				{
					if(_ufle12jhs77_unityAudioClipField==null || _ufle12jhs77_unityAudioClipField.IsDeleted) _ufle12jhs77_unityAudioClipField=(BansheeGz.BGDatabase.BGFieldUnityAudioClip) MetaDefault.GetField(new BGId(4825868847504134564,2434145578512012470));
					return _ufle12jhs77_unityAudioClipField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityFont _ufle12jhs77_unityFontField;
			public static BansheeGz.BGDatabase.BGFieldUnityFont _unityFontField
			{
				get
				{
					if(_ufle12jhs77_unityFontField==null || _ufle12jhs77_unityFontField.IsDeleted) _ufle12jhs77_unityFontField=(BansheeGz.BGDatabase.BGFieldUnityFont) MetaDefault.GetField(new BGId(5599513016958909782,3230565417687017906));
					return _ufle12jhs77_unityFontField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityMaterial _ufle12jhs77_unityMaterialField;
			public static BansheeGz.BGDatabase.BGFieldUnityMaterial _unityMaterialField
			{
				get
				{
					if(_ufle12jhs77_unityMaterialField==null || _ufle12jhs77_unityMaterialField.IsDeleted) _ufle12jhs77_unityMaterialField=(BansheeGz.BGDatabase.BGFieldUnityMaterial) MetaDefault.GetField(new BGId(4908436488796322532,14604855426035245470));
					return _ufle12jhs77_unityMaterialField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityObject _ufle12jhs77_unityObjectField;
			public static BansheeGz.BGDatabase.BGFieldUnityObject _unityObjectField
			{
				get
				{
					if(_ufle12jhs77_unityObjectField==null || _ufle12jhs77_unityObjectField.IsDeleted) _ufle12jhs77_unityObjectField=(BansheeGz.BGDatabase.BGFieldUnityObject) MetaDefault.GetField(new BGId(4839494584961834536,2008211144111203502));
					return _ufle12jhs77_unityObjectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_unityPrefabField;
			public static BansheeGz.BGDatabase.BGFieldUnityPrefab _unityPrefabField
			{
				get
				{
					if(_ufle12jhs77_unityPrefabField==null || _ufle12jhs77_unityPrefabField.IsDeleted) _ufle12jhs77_unityPrefabField=(BansheeGz.BGDatabase.BGFieldUnityPrefab) MetaDefault.GetField(new BGId(5194638669282079054,358716183513871039));
					return _ufle12jhs77_unityPrefabField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_unitySpriteField;
			public static BansheeGz.BGDatabase.BGFieldUnitySprite _unitySpriteField
			{
				get
				{
					if(_ufle12jhs77_unitySpriteField==null || _ufle12jhs77_unitySpriteField.IsDeleted) _ufle12jhs77_unitySpriteField=(BansheeGz.BGDatabase.BGFieldUnitySprite) MetaDefault.GetField(new BGId(4669431258759682220,7562358095153627323));
					return _ufle12jhs77_unitySpriteField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture _ufle12jhs77_unityTextureField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture _unityTextureField
			{
				get
				{
					if(_ufle12jhs77_unityTextureField==null || _ufle12jhs77_unityTextureField.IsDeleted) _ufle12jhs77_unityTextureField=(BansheeGz.BGDatabase.BGFieldUnityTexture) MetaDefault.GetField(new BGId(5370240882512399954,13796868656774551469));
					return _ufle12jhs77_unityTextureField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture2d _ufle12jhs77_unityTexture2dField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture2d _unityTexture2dField
			{
				get
				{
					if(_ufle12jhs77_unityTexture2dField==null || _ufle12jhs77_unityTexture2dField.IsDeleted) _ufle12jhs77_unityTexture2dField=(BansheeGz.BGDatabase.BGFieldUnityTexture2d) MetaDefault.GetField(new BGId(4667378435442547491,6566432755137170102));
					return _ufle12jhs77_unityTexture2dField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _ufle12jhs77_spriteMultiple;
			public static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _spriteMultiple
			{
				get
				{
					if(_ufle12jhs77_spriteMultiple==null || _ufle12jhs77_spriteMultiple.IsDeleted) _ufle12jhs77_spriteMultiple=(BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple) MetaDefault.GetField(new BGId(5428695482298794185,14203080233642320273));
					return _ufle12jhs77_spriteMultiple;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			[UIHint(UIHint.Variable)]
			public FsmString name;
			[UIHint(UIHint.Variable)]
			public FsmBool boolField;
			[UIHint(UIHint.Variable)]
			public FsmFloat floatField;
			[UIHint(UIHint.Variable)]
			public FsmInt intField;
			[UIHint(UIHint.Variable)]
			public FsmString stringField;
			[UIHint(UIHint.Variable)]
			public FsmString textField;
			[UIHint(UIHint.Variable)]
			public FsmColor colorField;
			[UIHint(UIHint.Variable)]
			public FsmQuaternion quaternionField;
			[UIHint(UIHint.Variable)]
			public FsmRect rectField;
			[UIHint(UIHint.Variable)]
			public FsmVector2 vector2Field;
			[UIHint(UIHint.Variable)]
			public FsmVector3 vector3Field;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.AudioClip))]
			public FsmObject unityAudioClipField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Font))]
			public FsmObject unityFontField;
			[UIHint(UIHint.Variable)]
			public FsmMaterial unityMaterialField;
			[UIHint(UIHint.Variable)]
			public FsmObject unityObjectField;
			[UIHint(UIHint.Variable)]
			public FsmGameObject unityPrefabField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Sprite))]
			public FsmObject unitySpriteField;
			[UIHint(UIHint.Variable)]
			public FsmTexture unityTextureField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Texture2D))]
			public FsmObject unityTexture2dField;
			[UIHint(UIHint.Variable)]
			[ArrayEditor(VariableType.Object)]
			public FsmArray spriteMultiple;
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entity id")]
			public FsmString _Id;
			public override void Reset()
			{
				_Id = null;
				_Index = null;
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
				unityAudioClipField = null;
				unityFontField = null;
				unityMaterialField = null;
				unityObjectField = null;
				unityPrefabField = null;
				unitySpriteField = null;
				unityTextureField = null;
				unityTexture2dField = null;
				spriteMultiple = null;
			}
			public override void OnEnter()
			{
				if (_Index.IsNone)
				{
					Debug.LogWarning("Required field _Index is not set");
					return;
				}
				var index = _Index.Value;
				if(!_Id.IsNone)
				{
					_Id.Value = MetaDefault.GetEntity(index).Id.ToString();
				}
				if(!name.IsNone)
				{
					name.Value = _name[index];
				}
				if(!boolField.IsNone)
				{
					boolField.Value = _boolField[index];
				}
				if(!floatField.IsNone)
				{
					floatField.Value = _floatField[index];
				}
				if(!intField.IsNone)
				{
					intField.Value = _intField[index];
				}
				if(!stringField.IsNone)
				{
					stringField.Value = _stringField[index];
				}
				if(!textField.IsNone)
				{
					textField.Value = _textField[index];
				}
				if(!colorField.IsNone)
				{
					colorField.Value = _colorField[index];
				}
				if(!quaternionField.IsNone)
				{
					quaternionField.Value = _quaternionField[index];
				}
				if(!rectField.IsNone)
				{
					rectField.Value = _rectField[index];
				}
				if(!vector2Field.IsNone)
				{
					vector2Field.Value = _vector2Field[index];
				}
				if(!vector3Field.IsNone)
				{
					vector3Field.Value = _vector3Field[index];
				}
				if(!unityAudioClipField.IsNone)
				{
					unityAudioClipField.Value = _unityAudioClipField[index];
				}
				if(!unityFontField.IsNone)
				{
					unityFontField.Value = _unityFontField[index];
				}
				if(!unityMaterialField.IsNone)
				{
					unityMaterialField.Value = _unityMaterialField[index];
				}
				if(!unityObjectField.IsNone)
				{
					unityObjectField.Value = _unityObjectField[index];
				}
				if(!unityPrefabField.IsNone)
				{
					unityPrefabField.Value = _unityPrefabField[index];
				}
				if(!unitySpriteField.IsNone)
				{
					unitySpriteField.Value = _unitySpriteField[index];
				}
				if(!unityTextureField.IsNone)
				{
					unityTextureField.Value = _unityTextureField[index];
				}
				if(!unityTexture2dField.IsNone)
				{
					unityTexture2dField.Value = _unityTexture2dField[index];
				}
				if(!spriteMultiple.IsNone)
				{
					var list = _spriteMultiple[index];
					if (list != null && list.Length > 0) spriteMultiple.Values = list;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Set row data for AllFields meta from GameRepo database by row's index")]
		public partial class AllFieldsSetByIndex : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			public FsmString name;
			public FsmBool boolField;
			public FsmFloat floatField;
			public FsmInt intField;
			public FsmString stringField;
			public FsmString textField;
			public FsmColor colorField;
			public FsmQuaternion quaternionField;
			public FsmRect rectField;
			public FsmVector2 vector2Field;
			public FsmVector3 vector3Field;
			public override void Reset()
			{
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
			}
			public override void OnEnter()
			{
				if (_Index.IsNone)
				{
					Debug.LogWarning("Required field _Index is not set");
					return;
				}
				var index = _Index.Value;
				if(!name.IsNone)
				{
					_name[index] = name.Value;
				}
				if(!boolField.IsNone)
				{
					_boolField[index] = boolField.Value;
				}
				if(!floatField.IsNone)
				{
					_floatField[index] = floatField.Value;
				}
				if(!intField.IsNone)
				{
					_intField[index] = intField.Value;
				}
				if(!stringField.IsNone)
				{
					_stringField[index] = stringField.Value;
				}
				if(!textField.IsNone)
				{
					_textField[index] = textField.Value;
				}
				if(!colorField.IsNone)
				{
					_colorField[index] = colorField.Value;
				}
				if(!quaternionField.IsNone)
				{
					_quaternionField[index] = quaternionField.Value;
				}
				if(!rectField.IsNone)
				{
					_rectField[index] = rectField.Value;
				}
				if(!vector2Field.IsNone)
				{
					_vector2Field[index] = vector2Field.Value;
				}
				if(!vector3Field.IsNone)
				{
					_vector3Field[index] = vector3Field.Value;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Fetch row data for AllFields meta from GameRepo database by row's name")]
		public partial class AllFieldsGetByName : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityAudioClip _ufle12jhs77_unityAudioClipField;
			public static BansheeGz.BGDatabase.BGFieldUnityAudioClip _unityAudioClipField
			{
				get
				{
					if(_ufle12jhs77_unityAudioClipField==null || _ufle12jhs77_unityAudioClipField.IsDeleted) _ufle12jhs77_unityAudioClipField=(BansheeGz.BGDatabase.BGFieldUnityAudioClip) MetaDefault.GetField(new BGId(4825868847504134564,2434145578512012470));
					return _ufle12jhs77_unityAudioClipField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityFont _ufle12jhs77_unityFontField;
			public static BansheeGz.BGDatabase.BGFieldUnityFont _unityFontField
			{
				get
				{
					if(_ufle12jhs77_unityFontField==null || _ufle12jhs77_unityFontField.IsDeleted) _ufle12jhs77_unityFontField=(BansheeGz.BGDatabase.BGFieldUnityFont) MetaDefault.GetField(new BGId(5599513016958909782,3230565417687017906));
					return _ufle12jhs77_unityFontField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityMaterial _ufle12jhs77_unityMaterialField;
			public static BansheeGz.BGDatabase.BGFieldUnityMaterial _unityMaterialField
			{
				get
				{
					if(_ufle12jhs77_unityMaterialField==null || _ufle12jhs77_unityMaterialField.IsDeleted) _ufle12jhs77_unityMaterialField=(BansheeGz.BGDatabase.BGFieldUnityMaterial) MetaDefault.GetField(new BGId(4908436488796322532,14604855426035245470));
					return _ufle12jhs77_unityMaterialField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityObject _ufle12jhs77_unityObjectField;
			public static BansheeGz.BGDatabase.BGFieldUnityObject _unityObjectField
			{
				get
				{
					if(_ufle12jhs77_unityObjectField==null || _ufle12jhs77_unityObjectField.IsDeleted) _ufle12jhs77_unityObjectField=(BansheeGz.BGDatabase.BGFieldUnityObject) MetaDefault.GetField(new BGId(4839494584961834536,2008211144111203502));
					return _ufle12jhs77_unityObjectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_unityPrefabField;
			public static BansheeGz.BGDatabase.BGFieldUnityPrefab _unityPrefabField
			{
				get
				{
					if(_ufle12jhs77_unityPrefabField==null || _ufle12jhs77_unityPrefabField.IsDeleted) _ufle12jhs77_unityPrefabField=(BansheeGz.BGDatabase.BGFieldUnityPrefab) MetaDefault.GetField(new BGId(5194638669282079054,358716183513871039));
					return _ufle12jhs77_unityPrefabField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_unitySpriteField;
			public static BansheeGz.BGDatabase.BGFieldUnitySprite _unitySpriteField
			{
				get
				{
					if(_ufle12jhs77_unitySpriteField==null || _ufle12jhs77_unitySpriteField.IsDeleted) _ufle12jhs77_unitySpriteField=(BansheeGz.BGDatabase.BGFieldUnitySprite) MetaDefault.GetField(new BGId(4669431258759682220,7562358095153627323));
					return _ufle12jhs77_unitySpriteField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture _ufle12jhs77_unityTextureField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture _unityTextureField
			{
				get
				{
					if(_ufle12jhs77_unityTextureField==null || _ufle12jhs77_unityTextureField.IsDeleted) _ufle12jhs77_unityTextureField=(BansheeGz.BGDatabase.BGFieldUnityTexture) MetaDefault.GetField(new BGId(5370240882512399954,13796868656774551469));
					return _ufle12jhs77_unityTextureField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnityTexture2d _ufle12jhs77_unityTexture2dField;
			public static BansheeGz.BGDatabase.BGFieldUnityTexture2d _unityTexture2dField
			{
				get
				{
					if(_ufle12jhs77_unityTexture2dField==null || _ufle12jhs77_unityTexture2dField.IsDeleted) _ufle12jhs77_unityTexture2dField=(BansheeGz.BGDatabase.BGFieldUnityTexture2d) MetaDefault.GetField(new BGId(4667378435442547491,6566432755137170102));
					return _ufle12jhs77_unityTexture2dField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _ufle12jhs77_spriteMultiple;
			public static BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple _spriteMultiple
			{
				get
				{
					if(_ufle12jhs77_spriteMultiple==null || _ufle12jhs77_spriteMultiple.IsDeleted) _ufle12jhs77_spriteMultiple=(BansheeGz.BGDatabase.BGFieldUnitySpriteMultiple) MetaDefault.GetField(new BGId(5428695482298794185,14203080233642320273));
					return _ufle12jhs77_spriteMultiple;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity Name")]
			public FsmString _Name;
			[UIHint(UIHint.Variable)]
			public FsmString name;
			[UIHint(UIHint.Variable)]
			public FsmBool boolField;
			[UIHint(UIHint.Variable)]
			public FsmFloat floatField;
			[UIHint(UIHint.Variable)]
			public FsmInt intField;
			[UIHint(UIHint.Variable)]
			public FsmString stringField;
			[UIHint(UIHint.Variable)]
			public FsmString textField;
			[UIHint(UIHint.Variable)]
			public FsmColor colorField;
			[UIHint(UIHint.Variable)]
			public FsmQuaternion quaternionField;
			[UIHint(UIHint.Variable)]
			public FsmRect rectField;
			[UIHint(UIHint.Variable)]
			public FsmVector2 vector2Field;
			[UIHint(UIHint.Variable)]
			public FsmVector3 vector3Field;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.AudioClip))]
			public FsmObject unityAudioClipField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Font))]
			public FsmObject unityFontField;
			[UIHint(UIHint.Variable)]
			public FsmMaterial unityMaterialField;
			[UIHint(UIHint.Variable)]
			public FsmObject unityObjectField;
			[UIHint(UIHint.Variable)]
			public FsmGameObject unityPrefabField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Sprite))]
			public FsmObject unitySpriteField;
			[UIHint(UIHint.Variable)]
			public FsmTexture unityTextureField;
			[UIHint(UIHint.Variable)]
			[ObjectType(typeof(UnityEngine.Texture2D))]
			public FsmObject unityTexture2dField;
			[UIHint(UIHint.Variable)]
			[ArrayEditor(VariableType.Object)]
			public FsmArray spriteMultiple;
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entity id")]
			public FsmString _Id;
			public override void Reset()
			{
				_Id = null;
				_Index = null;
				_Name=null;
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
				unityAudioClipField = null;
				unityFontField = null;
				unityMaterialField = null;
				unityObjectField = null;
				unityPrefabField = null;
				unitySpriteField = null;
				unityTextureField = null;
				unityTexture2dField = null;
				spriteMultiple = null;
			}
			public override void OnEnter()
			{
				if (_Name.IsNone)
				{
					Debug.LogWarning("Required field _Name is not set");
					return;
				}
				var meta = BGRepo.I.GetMeta("AllFields");
				if (meta == null)
				{
					Debug.LogWarning("No meta found, name=AllFields");
					return;
				}
				var entity = meta[_Name.Value];
				if (entity == null)
				{
					Debug.LogWarning("No entity found, name=" + _Name.Value);
					return;
				}
				var index = entity.Index;
				if(!_Index.IsNone)
				{
					_Index.Value = index;
				}
				if(!_Id.IsNone)
				{
					_Id.Value = entity.Id.ToString();
				}
				if(!name.IsNone)
				{
					name.Value = _name[index];
				}
				if(!boolField.IsNone)
				{
					boolField.Value = _boolField[index];
				}
				if(!floatField.IsNone)
				{
					floatField.Value = _floatField[index];
				}
				if(!intField.IsNone)
				{
					intField.Value = _intField[index];
				}
				if(!stringField.IsNone)
				{
					stringField.Value = _stringField[index];
				}
				if(!textField.IsNone)
				{
					textField.Value = _textField[index];
				}
				if(!colorField.IsNone)
				{
					colorField.Value = _colorField[index];
				}
				if(!quaternionField.IsNone)
				{
					quaternionField.Value = _quaternionField[index];
				}
				if(!rectField.IsNone)
				{
					rectField.Value = _rectField[index];
				}
				if(!vector2Field.IsNone)
				{
					vector2Field.Value = _vector2Field[index];
				}
				if(!vector3Field.IsNone)
				{
					vector3Field.Value = _vector3Field[index];
				}
				if(!unityAudioClipField.IsNone)
				{
					unityAudioClipField.Value = _unityAudioClipField[index];
				}
				if(!unityFontField.IsNone)
				{
					unityFontField.Value = _unityFontField[index];
				}
				if(!unityMaterialField.IsNone)
				{
					unityMaterialField.Value = _unityMaterialField[index];
				}
				if(!unityObjectField.IsNone)
				{
					unityObjectField.Value = _unityObjectField[index];
				}
				if(!unityPrefabField.IsNone)
				{
					unityPrefabField.Value = _unityPrefabField[index];
				}
				if(!unitySpriteField.IsNone)
				{
					unitySpriteField.Value = _unitySpriteField[index];
				}
				if(!unityTextureField.IsNone)
				{
					unityTextureField.Value = _unityTextureField[index];
				}
				if(!unityTexture2dField.IsNone)
				{
					unityTexture2dField.Value = _unityTexture2dField[index];
				}
				if(!spriteMultiple.IsNone)
				{
					var list = _spriteMultiple[index];
					if (list != null && list.Length > 0) spriteMultiple.Values = list;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Set row data for AllFields meta from GameRepo database by row's name")]
		public partial class AllFieldsSetByName : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity Name")]
			public FsmString _Name;
			public FsmString name;
			public FsmBool boolField;
			public FsmFloat floatField;
			public FsmInt intField;
			public FsmString stringField;
			public FsmString textField;
			public FsmColor colorField;
			public FsmQuaternion quaternionField;
			public FsmRect rectField;
			public FsmVector2 vector2Field;
			public FsmVector3 vector3Field;
			public override void Reset()
			{
				_Name=null;
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
			}
			public override void OnEnter()
			{
				if (_Name.IsNone)
				{
					Debug.LogWarning("Required field _Name is not set");
					return;
				}
				var meta = BGRepo.I.GetMeta("AllFields");
				if (meta == null)
				{
					Debug.LogWarning("No meta found, name=AllFields");
					return;
				}
				var entity = meta[_Name.Value];
				if (entity == null)
				{
					Debug.LogWarning("No entity found, name=" + _Name.Value);
					return;
				}
				var index = entity.Index;
				if(!name.IsNone)
				{
					_name[index] = name.Value;
				}
				if(!boolField.IsNone)
				{
					_boolField[index] = boolField.Value;
				}
				if(!floatField.IsNone)
				{
					_floatField[index] = floatField.Value;
				}
				if(!intField.IsNone)
				{
					_intField[index] = intField.Value;
				}
				if(!stringField.IsNone)
				{
					_stringField[index] = stringField.Value;
				}
				if(!textField.IsNone)
				{
					_textField[index] = textField.Value;
				}
				if(!colorField.IsNone)
				{
					_colorField[index] = colorField.Value;
				}
				if(!quaternionField.IsNone)
				{
					_quaternionField[index] = quaternionField.Value;
				}
				if(!rectField.IsNone)
				{
					_rectField[index] = rectField.Value;
				}
				if(!vector2Field.IsNone)
				{
					_vector2Field[index] = vector2Field.Value;
				}
				if(!vector3Field.IsNone)
				{
					_vector3Field[index] = vector3Field.Value;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Get the number of rows for AllFields meta")]
		public partial class AllFieldsCount : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entities count")]
			public FsmInt Count;
			public override void OnEnter()
			{
				if(Count != null)
				{
					Count.Value = MetaDefault.CountEntities;
				}
				Finish();
			}
			public override void Reset()
			{
				Count = null;
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Create new row")]
		public partial class AllFieldsCreate : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5570286723991365285,11634226054763119254));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_boolField;
			public static BansheeGz.BGDatabase.BGFieldBool _boolField
			{
				get
				{
					if(_ufle12jhs77_boolField==null || _ufle12jhs77_boolField.IsDeleted) _ufle12jhs77_boolField=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4969010152952188409,1387120008964941235));
					return _ufle12jhs77_boolField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_floatField;
			public static BansheeGz.BGDatabase.BGFieldFloat _floatField
			{
				get
				{
					if(_ufle12jhs77_floatField==null || _ufle12jhs77_floatField.IsDeleted) _ufle12jhs77_floatField=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4781805971323986292,7229575562578327463));
					return _ufle12jhs77_floatField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_intField;
			public static BansheeGz.BGDatabase.BGFieldInt _intField
			{
				get
				{
					if(_ufle12jhs77_intField==null || _ufle12jhs77_intField.IsDeleted) _ufle12jhs77_intField=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5062202591277125531,13470400415007099327));
					return _ufle12jhs77_intField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_stringField;
			public static BansheeGz.BGDatabase.BGFieldString _stringField
			{
				get
				{
					if(_ufle12jhs77_stringField==null || _ufle12jhs77_stringField.IsDeleted) _ufle12jhs77_stringField=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5218641453975102724,10159671019694477207));
					return _ufle12jhs77_stringField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldText _ufle12jhs77_textField;
			public static BansheeGz.BGDatabase.BGFieldText _textField
			{
				get
				{
					if(_ufle12jhs77_textField==null || _ufle12jhs77_textField.IsDeleted) _ufle12jhs77_textField=(BansheeGz.BGDatabase.BGFieldText) MetaDefault.GetField(new BGId(4879638100388443870,14609636118163167372));
					return _ufle12jhs77_textField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldColor _ufle12jhs77_colorField;
			public static BansheeGz.BGDatabase.BGFieldColor _colorField
			{
				get
				{
					if(_ufle12jhs77_colorField==null || _ufle12jhs77_colorField.IsDeleted) _ufle12jhs77_colorField=(BansheeGz.BGDatabase.BGFieldColor) MetaDefault.GetField(new BGId(5436783966389924427,5317331997240768929));
					return _ufle12jhs77_colorField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_quaternionField;
			public static BansheeGz.BGDatabase.BGFieldQuaternion _quaternionField
			{
				get
				{
					if(_ufle12jhs77_quaternionField==null || _ufle12jhs77_quaternionField.IsDeleted) _ufle12jhs77_quaternionField=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5021255907326914143,385316719601118399));
					return _ufle12jhs77_quaternionField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldRect _ufle12jhs77_rectField;
			public static BansheeGz.BGDatabase.BGFieldRect _rectField
			{
				get
				{
					if(_ufle12jhs77_rectField==null || _ufle12jhs77_rectField.IsDeleted) _ufle12jhs77_rectField=(BansheeGz.BGDatabase.BGFieldRect) MetaDefault.GetField(new BGId(5060252708445286492,5004618144396890303));
					return _ufle12jhs77_rectField;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_vector2Field;
			public static BansheeGz.BGDatabase.BGFieldVector2 _vector2Field
			{
				get
				{
					if(_ufle12jhs77_vector2Field==null || _ufle12jhs77_vector2Field.IsDeleted) _ufle12jhs77_vector2Field=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(4922966552026156052,17569026196120267679));
					return _ufle12jhs77_vector2Field;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_vector3Field;
			public static BansheeGz.BGDatabase.BGFieldVector3 _vector3Field
			{
				get
				{
					if(_ufle12jhs77_vector3Field==null || _ufle12jhs77_vector3Field.IsDeleted) _ufle12jhs77_vector3Field=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4849307352311183441,8619096549739073922));
					return _ufle12jhs77_vector3Field;
				}
			}
			public FsmString name;
			public FsmBool boolField;
			public FsmFloat floatField;
			public FsmInt intField;
			public FsmString stringField;
			public FsmString textField;
			public FsmColor colorField;
			public FsmQuaternion quaternionField;
			public FsmRect rectField;
			public FsmVector2 vector2Field;
			public FsmVector3 vector3Field;
			[UIHint(UIHint.Variable)]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			public override void Reset()
			{
				name = null;
				boolField = null;
				floatField = null;
				intField = null;
				stringField = null;
				textField = null;
				colorField = null;
				quaternionField = null;
				rectField = null;
				vector2Field = null;
				vector3Field = null;
			}
			public override void OnEnter()
			{
				var entity = MetaDefault.NewEntity();
				var index = entity.Index;
				if(!_Index.IsNone)
				{
					_Index.Value = index;
				}
				if(!name.IsNone)
				{
					_name[index] = name.Value;
				}
				if(!boolField.IsNone)
				{
					_boolField[index] = boolField.Value;
				}
				if(!floatField.IsNone)
				{
					_floatField[index] = floatField.Value;
				}
				if(!intField.IsNone)
				{
					_intField[index] = intField.Value;
				}
				if(!stringField.IsNone)
				{
					_stringField[index] = stringField.Value;
				}
				if(!textField.IsNone)
				{
					_textField[index] = textField.Value;
				}
				if(!colorField.IsNone)
				{
					_colorField[index] = colorField.Value;
				}
				if(!quaternionField.IsNone)
				{
					_quaternionField[index] = quaternionField.Value;
				}
				if(!rectField.IsNone)
				{
					_rectField[index] = rectField.Value;
				}
				if(!vector2Field.IsNone)
				{
					_vector2Field[index] = vector2Field.Value;
				}
				if(!vector3Field.IsNone)
				{
					_vector3Field[index] = vector3Field.Value;
				}
				Finish();
			}
		}


		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		[ActionCategory("BansheeGz")]
		[HutongGames.PlayMaker.Tooltip("Delete the row by its index for AllFields meta")]
		public partial class AllFieldsDelete : FsmStateAction
		{
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4819454853643778323,902013229545896621));
					return _metaDefault;
				}
			}
			[RequiredField]
			[HutongGames.PlayMaker.Tooltip("Entity index")]
			public FsmInt _Index;
			public override void OnEnter()
			{
				if (_Index.IsNone)
				{
					Debug.LogWarning("Required field _Index is not set");
					return;
				}
				if (_Index.Value < 0)
				{
					Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
					return;
				}
				if (_Index.Value >= MetaDefault.CountEntities)
				{
					Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
					return;
				}
				var entity = MetaDefault.GetEntity(_Index.Value);
				entity.Delete();
				Finish();
			}
			public override void Reset()
			{
				_Index = null;
			}
		}

#endif
