#if PLAYMAKER
using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;
using HutongGames.PlayMaker.Actions;
using HutongGames.PlayMaker;
using UnityEngine;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class CARDGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5053070866147318265UL, 5992202951562131636UL), () => _ufle12jhs77_sprite = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt atk;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Id = new FsmString{UseVariable = true};
		name = null;
		name_text = null;
		atk = null;
		sprite = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!atk.IsNone)
		{
			atk.Value = __generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class CARDSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmString name_text;
	public FsmInt atk;
	public override void Reset()
	{
		_Id = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		atk = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!atk.IsNone)
		{
			__generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index] = atk.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class CARDGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5053070866147318265UL, 5992202951562131636UL), () => _ufle12jhs77_sprite = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt atk;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Index = new FsmInt{UseVariable = true};
		name = null;
		name_text = null;
		atk = null;
		sprite = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!atk.IsNone)
		{
			atk.Value = __generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class CARDSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmString name_text;
	public FsmInt atk;
	public override void Reset()
	{
		_Index = new FsmInt{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		atk = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!atk.IsNone)
		{
			__generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index] = atk.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class CARDGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldUnitySprite _ufle12jhs77_sprite;
	public static BansheeGz.BGDatabase.BGFieldUnitySprite __generatedField___sprite => _ufle12jhs77_sprite ?? (_ufle12jhs77_sprite = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnitySprite>(MetaDefault, new BGId(5053070866147318265UL, 5992202951562131636UL), () => _ufle12jhs77_sprite = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt atk;
	[UIHint(UIHint.Variable)]
	[ObjectType(typeof(UnityEngine.Sprite))]
	public FsmObject sprite;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name = new FsmString{UseVariable = true};
		name = null;
		name_text = null;
		atk = null;
		sprite = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("CARD");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=CARD");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!atk.IsNone)
		{
			atk.Value = __generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!sprite.IsNone)
		{
			sprite.Value = __generatedField___sprite[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class CARDSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmString name_text;
	public FsmInt atk;
	public override void Reset()
	{
		_Name = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		atk = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("CARD");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=CARD");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!atk.IsNone)
		{
			__generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index] = atk.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for CARD meta")]
public partial class CARDCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class CARDCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5143358897583994798UL, 6285990645827097497UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5042302853236200244UL, 8824820891137873550UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5533205224230980473UL, 16695902370006601887UL), () => _ufle12jhs77_atk = null));
	public FsmString name;
	public FsmString name_text;
	public FsmInt atk;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		atk = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!name_text.IsNone)
			{
				__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
			}
			if(!atk.IsNone)
			{
				__generatedField___atk[as_dfa_fghsafa475_fasdfr3wetjr_index] = atk.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for CARD meta")]
public partial class CARDDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4850999173461448583UL,12629569426934860466UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class CARD_DECKGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt card_id;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Id = new FsmString{UseVariable = true};
		name = null;
		card_id = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!card_id.IsNone)
		{
			card_id.Value = __generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class CARD_DECKSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmInt card_id;
	public override void Reset()
	{
		_Id = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		card_id = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!card_id.IsNone)
		{
			__generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index] = card_id.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class CARD_DECKGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt card_id;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Index = new FsmInt{UseVariable = true};
		name = null;
		card_id = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!card_id.IsNone)
		{
			card_id.Value = __generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class CARD_DECKSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmInt card_id;
	public override void Reset()
	{
		_Index = new FsmInt{UseVariable = true};
		name = new FsmString{UseVariable = true};
		card_id = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!card_id.IsNone)
		{
			__generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index] = card_id.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class CARD_DECKGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmInt card_id;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name = new FsmString{UseVariable = true};
		name = null;
		card_id = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("CARD_DECK");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=CARD_DECK");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!card_id.IsNone)
		{
			card_id.Value = __generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class CARD_DECKSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmInt card_id;
	public override void Reset()
	{
		_Name = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		card_id = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("CARD_DECK");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=CARD_DECK");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!card_id.IsNone)
		{
			__generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index] = card_id.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for CARD_DECK meta")]
public partial class CARD_DECKCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class CARD_DECKCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4903494745224467534UL, 13840345304590027418UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_card_id;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___card_id => _ufle12jhs77_card_id ?? (_ufle12jhs77_card_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5574080016358172493UL, 8104440270611540398UL), () => _ufle12jhs77_card_id = null));
	public FsmString name;
	public FsmInt card_id;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = new FsmString{UseVariable = true};
		card_id = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!card_id.IsNone)
			{
				__generatedField___card_id[as_dfa_fghsafa475_fasdfr3wetjr_index] = card_id.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for CARD_DECK meta")]
public partial class CARD_DECKDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4965480319585121257UL,263262235149930401UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's id")]
public partial class ENEMYGetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt hp;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Id = new FsmString{UseVariable = true};
		name = null;
		name_text = null;
		hp = null;
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!hp.IsNone)
		{
			hp.Value = __generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's id")]
public partial class ENEMYSetById : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	public FsmString name;
	public FsmString name_text;
	public FsmInt hp;
	public override void Reset()
	{
		_Id = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		hp = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Id.IsNone || _Id.Value==null)
		{
			Debug.LogWarning("Required field _Id is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_id = BGId.Empty;
		try
		{
			as_dfa_fghsafa475_fasdfr3wetjr_id = new BGId(_Id.Value);
		}
		catch
		{
			Debug.LogWarning("Unable to parse id " + _Id.Value);
			Finish();
			return;
		}
		var entity = MetaDefault[as_dfa_fghsafa475_fasdfr3wetjr_id];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, id=" + as_dfa_fghsafa475_fasdfr3wetjr_id);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!hp.IsNone)
		{
			__generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index] = hp.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's index")]
public partial class ENEMYGetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt hp;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Index = new FsmInt{UseVariable = true};
		name = null;
		name_text = null;
		hp = null;
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = MetaDefault.GetEntity(as_dfa_fghsafa475_fasdfr3wetjr_index).Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!hp.IsNone)
		{
			hp.Value = __generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's index")]
public partial class ENEMYSetByIndex : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public FsmString name;
	public FsmString name_text;
	public FsmInt hp;
	public override void Reset()
	{
		_Index = new FsmInt{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		hp = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = _Index.Value;
		if (as_dfa_fghsafa475_fasdfr3wetjr_index < 0 || as_dfa_fghsafa475_fasdfr3wetjr_index >= MetaDefault.CountEntities)
		{
			Debug.LogError("_Index is out of range, it's < 0 or >= entities count.");
			Finish();
			return;
		}
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!hp.IsNone)
		{
			__generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index] = hp.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Fetch row data for $ meta from GameRepo database by row's name")]
public partial class ENEMYGetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	[UIHint(UIHint.Variable)]
	public FsmString name;
	[UIHint(UIHint.Variable)]
	public FsmString name_text;
	[UIHint(UIHint.Variable)]
	public FsmInt hp;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity id")]
	public FsmString _Id;
	[HutongGames.PlayMaker.Tooltip("Event is fired if entity was not found")]
	public FsmEvent _NotFoundEvent;
	public override void Reset()
	{
		_Id = null;
		_Index = null;
		_Name = new FsmString{UseVariable = true};
		name = null;
		name_text = null;
		hp = null;
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("ENEMY");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=ENEMY");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			if(!_Index.IsNone)
			{
				_Index.Value = -1;
			}
			Fsm.Event(_NotFoundEvent);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!_Index.IsNone)
		{
			_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
		}
		if(!_Id.IsNone)
		{
			_Id.Value = entity.Id.ToString();
		}
		if(!name.IsNone)
		{
			name.Value = __generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!name_text.IsNone)
		{
			name_text.Value = __generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		if(!hp.IsNone)
		{
			hp.Value = __generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index];
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Set row data for $ meta from GameRepo database by row's name")]
public partial class ENEMYSetByName : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity Name")]
	public FsmString _Name;
	public FsmString name;
	public FsmString name_text;
	public FsmInt hp;
	public override void Reset()
	{
		_Name = new FsmString{UseVariable = true};
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		hp = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		if (_Name.IsNone)
		{
			Debug.LogWarning("Required field _Name is not set");
			Finish();
			return;
		}
		var meta = BGRepo.I.GetMeta("ENEMY");
		if (meta == null)
		{
			Debug.LogWarning("No meta found, name=ENEMY");
			Finish();
			return;
		}
		var entity = meta[_Name.Value];
		if (entity == null)
		{
			Debug.LogWarning("No entity found, name=" + _Name.Value);
			Finish();
			return;
		}
		var as_dfa_fghsafa475_fasdfr3wetjr_index = entity.Index;
		if(!name.IsNone)
		{
			__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
		}
		if(!name_text.IsNone)
		{
			__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
		}
		if(!hp.IsNone)
		{
			__generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index] = hp.Value;
		}
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Get the number of rows for ENEMY meta")]
public partial class ENEMYCount : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entities count")]
	public FsmInt Count;
	public override void OnEnter()
	{
		if(Count != null)
		{
			Count.Value = MetaDefault.CountEntities;
		}
		Finish();
	}
	public override void Reset() => Count = null;
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Create new row")]
public partial class ENEMYCreate : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __generatedField___name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4612038125015537352UL, 7870811177069923460UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_name_text;
	public static BansheeGz.BGDatabase.BGFieldString __generatedField___name_text => _ufle12jhs77_name_text ?? (_ufle12jhs77_name_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5644455984657594627UL, 8616495024331366538UL), () => _ufle12jhs77_name_text = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt __generatedField___hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763064260743042073UL, 13436355263613966467UL), () => _ufle12jhs77_hp = null));
	public FsmString name;
	public FsmString name_text;
	public FsmInt hp;
	[UIHint(UIHint.Variable)]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void Reset()
	{
		name = new FsmString{UseVariable = true};
		name_text = new FsmString{UseVariable = true};
		hp = new FsmInt{UseVariable = true};
	}
	public override void OnEnter()
	{
		MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(___e => {
			var as_dfa_fghsafa475_fasdfr3wetjr_index = ___e.Index;
			if(!_Index.IsNone)
			{
				_Index.Value = as_dfa_fghsafa475_fasdfr3wetjr_index;
			}
			if(!name.IsNone)
			{
				__generatedField___name[as_dfa_fghsafa475_fasdfr3wetjr_index] = name.Value;
			}
			if(!name_text.IsNone)
			{
				__generatedField___name_text[as_dfa_fghsafa475_fasdfr3wetjr_index] = name_text.Value;
			}
			if(!hp.IsNone)
			{
				__generatedField___hp[as_dfa_fghsafa475_fasdfr3wetjr_index] = hp.Value;
			}
		}));
		Finish();
	}
}

[ActionCategory("BansheeGz")]
[HutongGames.PlayMaker.Tooltip("Delete the row by its index for ENEMY meta")]
public partial class ENEMYDelete : FsmStateAction
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5757897004548025251UL,648670655498662585UL), () => _metaDefault = null));
	[RequiredField]
	[HutongGames.PlayMaker.Tooltip("Entity index")]
	public FsmInt _Index;
	public override void OnEnter()
	{
		if (_Index.IsNone)
		{
			Debug.LogWarning("Required field _Index is not set");
			Finish();
			return;
		}
		if (_Index.Value < 0)
		{
			Debug.LogWarning("Unable to delete, index is less than zero: " + _Index.Value);
			Finish();
			return;
		}
		if (_Index.Value >= MetaDefault.CountEntities)
		{
			Debug.LogWarning("Unable to delete, index is equal or greater than number of rows: " + _Index.Value +">=" + MetaDefault.CountEntities);
			Finish();
			return;
		}
		var entity = MetaDefault.GetEntity(_Index.Value);
		entity.Delete();
		Finish();
	}
	public override void Reset() => _Index = null;
}
#pragma warning restore 414
#endif
